### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by ann-qb** [ann-qb/dashboard#12]
- [x] Website name placeholder must be something other than Dashboard as it could be confused with the dashboard page.
- [x] Copyright message in footer might look better center-aligned.
- [x] DisplayMessage component text might also look better center-aligned.

**Comment by Thejus5** [comment]
### Website name in header
The header is supposed to hold the name of the website. As of now the project does not have a name (it's just called 'dashboard project'). So the 'Dashboard' text is just a placeholder for the company / page name.

It will be replaced once the naming is done.

**Comment by Thejus5** [comment]
### Center alignment of footer text has been implemented

**Comment by Thejus5** [comment]
### Message text has been center aligned

**Comment by Thejus5** [comment]
### All issues fixed

 ![celebration](https://media.giphy.com/media/lN3KeOSg45ttl01qZV/giphy.gif)
